.TH "scripts/inc Directory Reference" 3 "Tue Mar 24 2015" "Version 0.2.3" "Cavrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/inc Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcolorterm\&.inc\fP"
.br
.ti -1c
.RI "file \fBdefinitions\&.inc\fP"
.br
.ti -1c
.RI "file \fBdetect_distro\&.inc\fP"
.br
.ti -1c
.RI "file \fBerr\&.inc\fP"
.br
.ti -1c
.RI "file \fBinstall\&.inc\fP"
.br
.ti -1c
.RI "file \fBinstaller\&.inc\fP"
.br
.in -1c
