.TH "src/Uart Directory Reference" 3 "Tue Mar 24 2015" "Version 0.2.3" "Cavrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Uart Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBuart\&.h\fP"
.br
.RI "\fI\fBUart\fP uses a variety of internal functions and presents them in the form of a \fBuart_t\fP object called \fBUart\fP\&. To access a function and its operations, simply address the function pointer\&. Check the examples for more\&. \fP"
.in -1c
