.TH "scripts/usr Directory Reference" 3 "Tue Mar 24 2015" "Version 0.2.3" "Cavrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scripts/usr Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBarch_install\&.inc\fP"
.br
.ti -1c
.RI "file \fBarch_package\&.inc\fP"
.br
.ti -1c
.RI "file \fBdebian_install\&.inc\fP"
.br
.ti -1c
.RI "file \fBdebian_package\&.inc\fP"
.br
.ti -1c
.RI "file \fBhandle_args\&.inc\fP"
.br
.ti -1c
.RI "file \fBredhat_install\&.inc\fP"
.br
.ti -1c
.RI "file \fBredhat_package\&.inc\fP"
.br
.ti -1c
.RI "file \fBtest\&.inc\fP"
.br
.ti -1c
.RI "file \fBusage_content\&.inc\fP"
.br
.in -1c
