.TH "Uart Directory Reference" 3 "Thu Feb 19 2015" "Version 0.1" "Cavrn Sedimentary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Uart Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBuart\&.c\fP"
.br
.ti -1c
.RI "file \fBuart\&.h\fP"
.br
.RI "\fIEnables UART functionality via an easy to use structure\&. \fP"
.in -1c
