.TH "cavrn_t" 3 "Tue Mar 24 2015" "Version 0.2.3" "Cavrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cavrn_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void(*const \fBsetInterrupts\fP )(const bool)"
.br
.RI "\fI: Enables or disables global interrupts on your AVR MCU \fP"
.ti -1c
.RI "bool \fBinterruptsEnabled\fP"
.br
.RI "\fI: Signifies that interrupts are enabled/disabled\&. For use by other modules as well as users\&. \fP"
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cavrn from the source code\&.
