.TH "Cavrn" 3 "Tue Mar 24 2015" "Version 0.2.3" "Cavrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cavrn \- The main entry point for global \fBCavrn\fP functionality\&. Access \fBcavrn_t\fP \fBCavrn\fP's functionality by addressing its function pointers\&. Check the Examples page for more\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cavrn\&.h>\fP
.SH "Detailed Description"
.PP 
The main entry point for global \fBCavrn\fP functionality\&. Access \fBcavrn_t\fP \fBCavrn\fP's functionality by addressing its function pointers\&. Check the Examples page for more\&. 
.PP
\fBExamples: \fP
.in +1c
\fBCavrn/setInterrupts\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cavrn from the source code\&.
