.TH "Cavrn" 3 "Thu Feb 19 2015" "Version 0.1" "Cavrn Sedimentary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cavrn \- The main entry point for global \fBCavrn\fP functionality\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cavrn\&.h>\fP
.SH "Detailed Description"
.PP 
The main entry point for global \fBCavrn\fP functionality\&. 

Use \fBCavrn\fP like an object when performing operations\&. Ex\&. 
.PP
.nf
Cavrn\&.setInterrupts(ON); // Set global interrupts

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cavrn Sedimentary from the source code\&.
