.TH "cavrn_t" 3 "Thu Feb 19 2015" "Version 0.1" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cavrn_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cavrn\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void(* \fBsetInterrupts\fP )(const bool)"
.br
.ti -1c
.RI "bool \fBinterruptsEnabled\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool cavrn_t::interruptsEnabled"

.SS "void(* cavrn_t::setInterrupts) (const bool)"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
