.TH "cavrn_t" 3 "Tue Feb 17 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cavrn_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cavrn\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBsetInterrupts\fP )(const bool)"
.br
.ti -1c
.RI "bool \fBinterruptsEnabled\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool cavrn_t::interruptsEnabled"

.SS "void(* cavrn_t::setInterrupts) (const bool)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
