.TH "Invalid" 3 "Thu Feb 19 2015" "Version 0.1" "Cavrn Sedimentary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Invalid \- Invalid
.PP
These functions have another point of entry and should not be called directly\&. In fact, there is no \fBCavrn\fP function that should not be called through a struct\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBuart_tx\fP (const \fBbyte\fP data)"
.br
.ti -1c
.RI "\fBbyte\fP \fBuart_rx\fP ()"
.br
.ti -1c
.RI "void \fBuart_txstr\fP (const char *const string)"
.br
.ti -1c
.RI "void \fBuart_rxstr\fP (char *const string, const uint8_t len)"
.br
.ti -1c
.RI "\fBbyte\fP \fBuart_transfer\fP (const \fBbyte\fP data)"
.br
.ti -1c
.RI "void \fBuart_multi_transfer\fP (const \fBbyte\fP *const data, \fBbyte\fP *datain, const uint8_t *const len)"
.br
.ti -1c
.RI "void \fBuart_set_tx_interrupt\fP (const bool isInterrupt)"
.br
.ti -1c
.RI "void \fBuart_set_rx_interrupt\fP (const bool isInterrupt)"
.br
.ti -1c
.RI "void \fBuart_set_udre_interrupt\fP (const bool isInterrupt)"
.br
.ti -1c
.RI "void \fBuart_set_interrupts\fP (const bool isInterrupt)"
.br
.ti -1c
.RI "void \fBuart_txchr\fP (const char chr)"
.br
.RI "\fITransmits a character of information (signed 8bit integer) via UART\&. \fP"
.ti -1c
.RI "char \fBuart_rxchr\fP ()"
.br
.RI "\fIRecieves a character of information (signed 8 bit integer) via UART\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
These functions have another point of entry and should not be called directly\&. In fact, there is no \fBCavrn\fP function that should not be called through a struct\&. 

These functions should not be called\&.
.PP
.PP
.nf
Uart\&.init(ASYNC_MODE);
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "void uart_multi_transfer (const \fBbyte\fP *const data, \fBbyte\fP * datain, const uint8_t *const len)"

.SS "\fBbyte\fP uart_rx ()"

.SS "char uart_rxchr ()"

.PP
Recieves a character of information (signed 8 bit integer) via UART\&. 
.PP
\fBReturns:\fP
.RS 4
char 
.RE
.PP

.SS "void uart_rxstr (char *const string, const uint8_t len)"

.SS "void uart_set_interrupts (const bool isInterrupt)"

.SS "void uart_set_rx_interrupt (const bool isInterrupt)"

.SS "void uart_set_tx_interrupt (const bool isInterrupt)"

.SS "void uart_set_udre_interrupt (const bool isInterrupt)"

.SS "\fBbyte\fP uart_transfer (const \fBbyte\fP data)"

.SS "void uart_tx (const \fBbyte\fP data)"

.SS "void uart_txchr (const char chr)"

.PP
Transmits a character of information (signed 8bit integer) via UART\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconst\fP char* const data The data to be transmited 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void uart_txstr (const char *const string)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cavrn Sedimentary from the source code\&.
