.TH "md_README" 3 "Thu Feb 19 2015" "Version 0.1.0" "Cavrn AVR8 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- README 
# 
.SS "An easy to use and extremely flexible library for AVR Microcontrollers, written in pure C\&."
.PP
.SS "Supported: ATmega328p, ATmega103"
.PP
.SS "Coming Soon: ATtiny85"
.PP
.SS "\fBCavrn\fP is currently a work in progress\&. This readme is terribly out of date due to that\&."
.PP
\fBCavrn\fP library is built on avr-libc, compiled with avr-gcc and meant to be easy to use while still retaining flexibility per mmcu for professional situations\&. Each available function (uart,spi,nrf24) which I'll be calling a module has a static struct that can be treated as an object when performing its operations\&. \fBCavrn\fP takes techniques found in the arduino library (like how \fBCavrn\fP uses typedefs and defines to create more verbose types such as bool and byte, both of which mean a uint8_t but when used correctly your code becomes much more explicit) as well as borrows from multiple others across the internet (including the NRF24lo1 repo this was originally forked from) to combine them with good practices and solid compiler integration\&. 
.SS "*Please Note:*"
.PP
.SS "*Cavrn just started and so naturally it's continually changing\&. What you may have been used to one day may not be there or may be buggy the next\&. Come back in a month or so if you really want to use \fBCavrn\fP (without also developing it)\&. Furthermore, this README will likely be incomplete\&. View the doc/ folder or more up to date documentation (that is also incomplete)*"
.PP
.SS "Usage"
.PP
At the moment there is not an install script to create a shared library file and install via a package manager, but I have a handy script for that which I need to modify just a bit for it to work with this\&. For the time being you can simply download the repo and configure the \fCMakefile\fP to fit your needs\&. Then run \fCmake\fP and if your board is plugged in \fCmake upload\fP\&.
.PP
Check below for small code examples and keep an eye on the repo because I'll be adding extensive ones soon\&.
.PP
.SS "Requirements"
.PP
To compile \fBCavrn\fP you will need the avr-gcc suite as well as avr-libc\&. To upload you will need avrdude and to view serial data you can install screen and type \fCmake console\fP but for long term use I recommend minicom\&.
.PP
At the moment a board with an Atmega328p or Atmega103 is required, but this will change soon\&. If you have the interest, it would be very simple to add defines for a board that you own\&. Simply define each pin that will be used in the appropriate header file\&.
.PP
.SS "UART"
.PP
.SS "A library implementation for sending/recieving bytes or strings via UART pins\&."
.PP
\fBUart\fP is able to take advantage of all modes given by an MCU\&. Just provide it during initialization\&. \fInote: The AVR ATmega103 does not have available status control registers to determine half/full duplex so no mode is needed at initialization\&.\fP
.PP
` Uart\&.init(ASYNC_MODE) or Uart\&.init(SYNC_MODE) or Uart\&.init(MSPI_MODE) \fC \fBUart\fP relies on a BAUD definition at compile time because many preprocessor directives rely on it; one benefit of doing it this way is that no large 32bit integers have to be used (ex\&. Baud of 115200) another is the assurance that your baud rate is what you would expect throughout the program and finally no compute time is wasted on arithmatic to calculate baud rates or\fPF_OSC` clock rates or even to separate high and low values for the USART Baud Rate Register because the preprocessor computes it\&.
.PP
To Define the Baud rate add -DBAUD=9600 or any other rate to the compilation\&. For most situations, simply fill in the provided makefile\&. During the extent of your program you can change the BAUD by undefining BAUD and redefining it before reincluding the <util/setbaud\&.h> file\&. This sounds janky but the setbaud\&.h file is simply a collection of preprocessor directives which will only be present at compile time and infact avr-libc recommends this way\&.
.PP
Take this example to see how easy to use the \fBUart\fP library is (and eventually all of \fBCavrn\fP)\&. ```C #include 'Cavrn/uart\&.h'
.PP
int main(void) { Uart\&.init(ASYNC_MODE); Uart\&.txString('Device Initialized\\n\\r');
.PP
while(1){ uint8_t recieved = Uart\&.rxByte(); char text[128]; sprintf(text,'Devices Recieved Data: %d\\n\\rAnalyzing\&.\&.\&.',recieved); Uart\&.txString(text); } return 0; } ```
.PP
.SS "SPI (Almost Operational)"
.PP
.SS "A simple and elegant peripheral communication library\&."
.PP
The SPI library takes a fairly straight forward and simple process even further by encapsulating functions in a data safe manner with high pointer usage for optimization but still gives you the flexibility that you would have from coding it by hand\&.
.PP
You can choose from the 4 clock polarity modes provided by Atmel\&. 
.PP
By initializing SPI with one of the four modes like so\&.\&.\&. ```C #include 'Cavrn/spi\&.h'
.PP
int main(void){ /* To assign as a master device */ Spi\&.init(MASTER,SPI_MODE0,F_OSC16);
.PP
//or another way to assign as a master device (true is defined as part of \fBCavrn\fP) Spi\&.init(true,SPI_MODE0,F_OSC16);
.PP
// or as a slave device Spi\&.init(SLAVE,SPI_MODE2,F_OSC8);
.PP
// and the data order can be changed from MSB to LSB and back by using setDataOrder from Spi\&.\&.\&. Spi\&.setDataOrder(MSB_ORDER); //Spi\&.setDataOrder(true) try using\&.\&.\&.HIGH,OUT,ON instead of true
.PP
// or for least significant bit Spi\&.setDataOrder(LSB_ORDER); //Spi\&.setDataOrder(false);
.PP
Spi\&.setInterrupts(true); //Spi\&.setInterrupts(ON);
.PP
// To transfer via SPI char letter_L = 'L'; uint8_t recieved = Spi\&.transfer(letter_L); // To transfer large amounts byte[128] text; byte[128] out = 'Hello World'; Spi\&.multiTransfer(out,text,128);
.PP
Spi\&.disable();
.PP
return 0; } ``` 
.PP
 
.SS "NRF24 (Relies on SPI)"
.PP
.SS "Making wireless connectivity quick and painless\&."
.PP
This module enables the auto acknowledgement and auto retransmission features of the nrf24L01+ in static length payload mode\&.
.PP
These two features are basically the most important features of the nrf24L01+ modules\&. With this module, after you make a tranmission attempt, you'll know for sure wheter the slave device got your message properly or not with minimal MCU involvement\&. Also, nrf24L01+ chipsets automatically handle the retranmission of the same message if it they lost in transmission, up to o limited trials with adjustable delays in between attempts\&.
.PP
.SS "Usage"
.PP
.SS "Configuration"
.PP
Configuration of the module is simple\&. Max retransmission count is set to 15 and delays between each retranmission is set to 1000 us\&. Also the CRC is enabled with 1byte length\&. Data rate is set to 1Mbps\&.
.PP
Via the config function, you can chose the channel and the payload length\&. Max payload length is 32\&. After the config function the module automatically goes to RX mode\&. Payload length and the RF channel values have to be consistent among the devices\&.
.PP
```C /* initializes hardware pins */ Nrf24\&.init();
.PP
/* RF channel: #2 , payload length: 4 */ Nrf24\&.config(2,4) ``` 
.SS "Addressing"
.PP
Address length is 5 bytes\&. You can configure the transmit and receive addresses as follows: ```C uint8_t rx_mac[5] = {0xE7,0xE7,0xE7,0xE7,0xE7}; uint8_t tx_mac[5] = {0xD7,0xD7,0xD7,0xD7,0xD7};
.PP
/* Set the module's own address */ Nrf24\&.rxAddr(rx_mac);
.PP
/* Set the transmit address */ Nrf24\&.txAddr(tx_mac); ``` 
.SS "Transmit"
.PP
Let's say the payload length is set to 4 and you have the following payload\&. ```C uint8_t data_array[4];
.PP
data_array[0] = 0x00; data_array[1] = 0xAA; data_array[2] = 0x55; data_array[3] = 0xFF; ``\fC The basic transmit function is the\fPNrf24\&.txData()\fCfunction\&. The module automatically switches to the TX mode and power up if required\&. \fP``C /* Automatically goes to TX mode */ Nrf24\&.txData(data_array); ``\fC After the\fPNrf24\&.txData()\fC, you must wait for transmission to end\&. MCU can sleep or do another tasks during that period\&. \fP``C /* Wait for transmission to end */ while(Nrf24\&.isSending()); ``` After the transmission end, optionally you can make analysis on the last transmission attempt\&. ```C uint8_t temp;
.PP
/* Make analysis on last tranmission attempt */ temp = Nrf24\&.lastTxStatus();
.PP
if(temp == NRF24_TRANSMISSON_OK) { Uart\&.txString('Tranmission went OK\\r\\n'); } else if(temp == NRF24_MESSAGE_LOST) { Uart\&.txString('Message is lost \&.\&.\&.\\r\\n'); }
.PP
/* Retranmission count indicates the tranmission quality */ temp = Nrf24\&.badTxCount();
.PP
char msg[64]; sprintf(msg,'Retranmission count: %d\\r\\n',temp); Uart\&.txString(msg); ``` After the tranmission finishes, nrf24L01+ module stays in Standby mode\&. You can manually go back to RX mode: ```C /* Go back to RX mode \&.\&.\&. */ Nrf24\&.powerRx(); ``` Or you can power down the module to lower the current consumption\&. ```C /* Power down the module */ Nrf24\&.powerDown(); ``` 
.SS "Receive"
.PP
This library doesn't use the IRQ pin of the nrf24L01+ (yet) , therefore you need to poll the \fCNrf24\&.dataReady()\fP function periodically\&. Otherwise you might miss some packets\&.
.PP
Also, you need to be in RX mode in order to be able to receive messages\&.
.PP
\fCNrf24\&.dataReady()\fP function returns non-zero only if a valid payload is awaiting in the RX fifo\&. \fCNrf24\&.getData(uint8_t* buf)\fP function copies the received message into the given buffer\&. ```C uint8_t data_array[4];
.PP
if(nNrf24\&.dataReady()) { Nrf24\&.rxData(data_array); } ``` 
.SS "References"
.PP
This module is proudly and heavily based on the following libraries:
.PP
.IP "\(bu" 2
https://github.com/aaronds/arduino-nrf24l01
.IP "\(bu" 2
http://www.tinkerer.eu/AVRLib/nRF24L01 
.PP

