.TH "nrf24_t" 3 "Tue Mar 24 2015" "Version 0.2.3" "Cavrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nrf24_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void(* \fBinit\fP )()"
.br
.ti -1c
.RI "void(* \fBtxAddr\fP )(const \fBbyte\fP *const)"
.br
.ti -1c
.RI "void(* \fBrxAddr\fP )(const \fBbyte\fP *const)"
.br
.ti -1c
.RI "void(* \fBconfig\fP )(const uint8_t, const uint8_t)"
.br
.ti -1c
.RI "bool(* \fBdataReady\fP )()"
.br
.ti -1c
.RI "bool(* \fBisSending\fP )()"
.br
.ti -1c
.RI "uint8_t(* \fBgetStatus\fP )()"
.br
.ti -1c
.RI "bool(* \fBrxWaiting\fP )()"
.br
.ti -1c
.RI "void(* \fBtxData\fP )(const \fBbyte\fP *const)"
.br
.ti -1c
.RI "void(* \fBrxData\fP )(\fBbyte\fP *const)"
.br
.ti -1c
.RI "uint8_t(* \fBpaylength\fP )()"
.br
.ti -1c
.RI "uint8_t(* \fBlastTxStatus\fP )()"
.br
.ti -1c
.RI "uint8_t(* \fBbadTxCount\fP )()"
.br
.ti -1c
.RI "void(* \fBpowerRx\fP )()"
.br
.ti -1c
.RI "void(* \fBpowerTx\fP )()"
.br
.ti -1c
.RI "void(* \fBpowerDown\fP )()"
.br
.ti -1c
.RI "uint8_t \fBpayload_len\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cavrn from the source code\&.
