.TH "Nrf24/nrf24.c" 3 "Tue Feb 17 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Nrf24/nrf24.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'nrf24\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnrf24_init\fP ()"
.br
.ti -1c
.RI "void \fBnrf24_config\fP (const uint8_t channel, const uint8_t pay_length)"
.br
.ti -1c
.RI "void \fBnrf24_rx_address\fP (const uint8_t *const adr)"
.br
.ti -1c
.RI "uint8_t \fBnrf24_payload_length\fP ()"
.br
.ti -1c
.RI "void \fBnrf24_tx_address\fP (const uint8_t *const adr)"
.br
.ti -1c
.RI "bool \fBnrf24_dataReady\fP ()"
.br
.ti -1c
.RI "bool \fBnrf24_rxFifoEmpty\fP ()"
.br
.ti -1c
.RI "uint8_t \fBnrf24_payloadLength\fP ()"
.br
.ti -1c
.RI "void \fBnrf24_getData\fP (uint8_t *const data)"
.br
.ti -1c
.RI "uint8_t \fBnrf24_retransmissionCount\fP ()"
.br
.ti -1c
.RI "void \fBnrf24_send\fP (const uint8_t *const value)"
.br
.ti -1c
.RI "bool \fBnrf24_isSending\fP ()"
.br
.ti -1c
.RI "uint8_t \fBnrf24_getStatus\fP ()"
.br
.ti -1c
.RI "uint8_t \fBnrf24_lastMessageStatus\fP ()"
.br
.ti -1c
.RI "void \fBnrf24_powerUpRx\fP ()"
.br
.ti -1c
.RI "void \fBnrf24_powerUpTx\fP ()"
.br
.ti -1c
.RI "void \fBnrf24_powerDown\fP ()"
.br
.ti -1c
.RI "void \fBnrf24_configRegister\fP (const uint8_t reg, const uint8_t value)"
.br
.ti -1c
.RI "void \fBnrf24_readRegister\fP (const uint8_t reg, uint8_t *const value, const uint8_t len)"
.br
.ti -1c
.RI "void \fBnrf24_writeRegister\fP (const uint8_t reg, const uint8_t *const value, const uint8_t len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void nrf24_config (const uint8_t channel, const uint8_t pay_length)"

.SS "void nrf24_configRegister (const uint8_t reg, const uint8_t value)"

.SS "bool nrf24_dataReady ()"

.SS "void nrf24_getData (uint8_t *const data)"

.SS "uint8_t nrf24_getStatus ()"

.SS "void nrf24_init ()"

.SS "bool nrf24_isSending ()"

.SS "uint8_t nrf24_lastMessageStatus ()"

.SS "uint8_t nrf24_payload_length ()"

.SS "uint8_t nrf24_payloadLength ()"

.SS "void nrf24_powerDown ()"

.SS "void nrf24_powerUpRx ()"

.SS "void nrf24_powerUpTx ()"

.SS "void nrf24_readRegister (const uint8_t reg, uint8_t *const value, const uint8_t len)"

.SS "uint8_t nrf24_retransmissionCount ()"

.SS "void nrf24_rx_address (const uint8_t *const adr)"

.SS "bool nrf24_rxFifoEmpty ()"

.SS "void nrf24_send (const uint8_t *const value)"

.SS "void nrf24_tx_address (const uint8_t *const adr)"

.SS "void nrf24_writeRegister (const uint8_t reg, const uint8_t *const value, const uint8_t len)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
