.TH "nrf24_t" 3 "Thu Feb 19 2015" "Version 0.1.0" "Cavrn AVR8 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nrf24_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nrf24\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void(* \fBinit\fP )()"
.br
.ti -1c
.RI "void(* \fBtxAddr\fP )(const \fBbyte\fP *const)"
.br
.ti -1c
.RI "void(* \fBrxAddr\fP )(const \fBbyte\fP *const)"
.br
.ti -1c
.RI "void(* \fBconfig\fP )(const uint8_t, const uint8_t)"
.br
.ti -1c
.RI "bool(* \fBdataReady\fP )()"
.br
.ti -1c
.RI "bool(* \fBisSending\fP )()"
.br
.ti -1c
.RI "uint8_t(* \fBgetStatus\fP )()"
.br
.ti -1c
.RI "bool(* \fBrxWaiting\fP )()"
.br
.ti -1c
.RI "void(* \fBtxData\fP )(const \fBbyte\fP *const)"
.br
.ti -1c
.RI "void(* \fBrxData\fP )(\fBbyte\fP *const)"
.br
.ti -1c
.RI "uint8_t(* \fBpaylength\fP )()"
.br
.ti -1c
.RI "uint8_t(* \fBlastTxStatus\fP )()"
.br
.ti -1c
.RI "uint8_t(* \fBbadTxCount\fP )()"
.br
.ti -1c
.RI "void(* \fBpowerRx\fP )()"
.br
.ti -1c
.RI "void(* \fBpowerTx\fP )()"
.br
.ti -1c
.RI "void(* \fBpowerDown\fP )()"
.br
.ti -1c
.RI "uint8_t \fBpayload_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 224 of file nrf24\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t(* nrf24_t::badTxCount) ()"

.PP
Definition at line 246 of file nrf24\&.h\&.
.SS "void(* nrf24_t::config) (const uint8_t, const uint8_t)"

.PP
Definition at line 229 of file nrf24\&.h\&.
.SS "bool(* nrf24_t::dataReady) ()"

.PP
Definition at line 233 of file nrf24\&.h\&.
.SS "uint8_t(* nrf24_t::getStatus) ()"

.PP
Definition at line 235 of file nrf24\&.h\&.
.SS "void(* nrf24_t::init) ()"

.PP
Definition at line 226 of file nrf24\&.h\&.
.SS "bool(* nrf24_t::isSending) ()"

.PP
Definition at line 234 of file nrf24\&.h\&.
.SS "uint8_t(* nrf24_t::lastTxStatus) ()"

.PP
Definition at line 245 of file nrf24\&.h\&.
.SS "uint8_t(* nrf24_t::paylength) ()"

.PP
Definition at line 242 of file nrf24\&.h\&.
.SS "uint8_t nrf24_t::payload_len"

.PP
Definition at line 253 of file nrf24\&.h\&.
.SS "void(* nrf24_t::powerDown) ()"

.PP
Definition at line 251 of file nrf24\&.h\&.
.SS "void(* nrf24_t::powerRx) ()"

.PP
Definition at line 249 of file nrf24\&.h\&.
.SS "void(* nrf24_t::powerTx) ()"

.PP
Definition at line 250 of file nrf24\&.h\&.
.SS "void(* nrf24_t::rxAddr) (const \fBbyte\fP *const)"

.PP
Definition at line 228 of file nrf24\&.h\&.
.SS "void(* nrf24_t::rxData) (\fBbyte\fP *const)"

.PP
Definition at line 239 of file nrf24\&.h\&.
.SS "bool(* nrf24_t::rxWaiting) ()"

.PP
Definition at line 236 of file nrf24\&.h\&.
.SS "void(* nrf24_t::txAddr) (const \fBbyte\fP *const)"

.PP
Definition at line 227 of file nrf24\&.h\&.
.SS "void(* nrf24_t::txData) (const \fBbyte\fP *const)"

.PP
Definition at line 238 of file nrf24\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cavrn AVR8 Library from the source code\&.
