.TH "spi_t" 3 "Tue Mar 24 2015" "Version 0.2.3" "Cavrn" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spi_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void(* \fBinit\fP )(const bool, const \fBbyte\fP, const uint8_t)"
.br
.ti -1c
.RI "\fBbyte\fP(* \fBtransfer\fP )(const \fBbyte\fP)"
.br
.ti -1c
.RI "void(* \fBmultiTransfer\fP )(const uint8_t *const, uint8_t *const, const uint8_t)"
.br
.ti -1c
.RI "void(* \fBsetDataOrder\fP )(const bool)"
.br
.ti -1c
.RI "void(* \fBsetInterrupts\fP )(const bool)"
.br
.ti -1c
.RI "void(* \fBdisable\fP )()"
.br
.ti -1c
.RI "bool \fBinterruptsEnabled\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cavrn from the source code\&.
