.TH "spi_t" 3 "Wed Feb 18 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spi_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBinit\fP )(const bool, const \fBbyte\fP, const uint8_t)"
.br
.ti -1c
.RI "\fBbyte\fP(* \fBtransfer\fP )(const \fBbyte\fP)"
.br
.ti -1c
.RI "void(* \fBmultiTransfer\fP )(const uint8_t *const, uint8_t *const, const uint8_t)"
.br
.ti -1c
.RI "void(* \fBsetDataOrder\fP )(const bool)"
.br
.ti -1c
.RI "void(* \fBsetInterrupts\fP )(const bool)"
.br
.ti -1c
.RI "void(* \fBdisable\fP )()"
.br
.ti -1c
.RI "bool \fBinterruptsEnabled\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void(* spi_t::disable) ()"

.SS "void(* spi_t::init) (const bool, const \fBbyte\fP, const uint8_t)"

.SS "bool spi_t::interruptsEnabled"

.SS "void(* spi_t::multiTransfer) (const uint8_t *const, uint8_t *const, const uint8_t)"

.SS "void(* spi_t::setDataOrder) (const bool)"

.SS "void(* spi_t::setInterrupts) (const bool)"

.SS "\fBbyte\fP(* spi_t::transfer) (const \fBbyte\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
