.TH "uart.h" 3 "Thu Feb 19 2015" "Version 0.1.0" "Cavrn AVR8 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uart.h \- \fBUart\fP uses a variety of internal functions and presents them in the form of a \fBuart_t\fP object called \fBUart\fP\&. To access a function and its operations, simply address the function pointer\&. Check the examples for more\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'cavrn\&.h'\fP
.br
\fC#include <util/setbaud\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBuart_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRXLEN\fP   254"
.br
.ti -1c
.RI "#define \fBUART_START\fP()   UCSRB |= (1<<TXEN) | (1<<RXEN)"
.br
.RI "\fISet UCSRB with the TX and RX enable flags\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static \fBuart_t\fP \fBUart\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBUart\fP uses a variety of internal functions and presents them in the form of a \fBuart_t\fP object called \fBUart\fP\&. To access a function and its operations, simply address the function pointer\&. Check the examples for more\&. 


.PP
\fBVersion:\fP
.RS 4
0\&.1\&.0 (Sedimentary Olm) 
.RE
.PP
\fBAuthor:\fP
.RS 4
Max Mansfield 
.RE
.PP
\fBCopyright:\fP
.RS 4
GNU Public License v2 
.RE
.PP
\fBDate:\fP
.RS 4
February 19, 2015 
.RE
.PP

.PP
Definition in file \fBuart\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define RXLEN   254"

.PP
Definition at line 48 of file uart\&.h\&.
.SS "#define UART_START()   UCSRB |= (1<<TXEN) | (1<<RXEN)"

.PP
Set UCSRB with the TX and RX enable flags\&. 
.PP
Definition at line 206 of file uart\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "\fBuart_t\fP \fBUart\fP\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
  \&.init = &uart_init,
  
  \&.txByte = &uart_tx,
  \&.rxByte = &uart_rx,
  
  \&.txString = &uart_txstr,
  \&.rxString = &uart_rxstr,

  \&.transfer = &uart_transfer,
  \&.multiTransfer = &uart_multi_transfer,
  
  \&.setInterrupts = &uart_set_interrupts,
  \&.setUdreInterrupt = &uart_set_udre_interrupt,
  \&.setTxInterrupt = &uart_set_tx_interrupt,
  \&.setRxInterrupt = &uart_set_rx_interrupt,
  
  \&.printableCharsOnly = false
}
.fi
.PP
Definition at line 405 of file uart\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Cavrn AVR8 Library from the source code\&.
