.TH "Uart" 3 "Thu Feb 19 2015" "Version 0.1.0" "Cavrn AVR8 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Uart \- The way to control any \fBUart\fP functions is through this struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uart\&.h>\fP
.SH "Detailed Description"
.PP 
The way to control any \fBUart\fP functions is through this struct\&. 

Use \fBUart\fP like an object when performing operations 
.PP
\fBExamples: \fP
.in +1c
\fBUart/PrintableTx\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cavrn AVR8 Library from the source code\&.
