.TH "Uart" 3 "Thu Feb 19 2015" "Version 0.1" "Cavrn Sedimentary" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Uart \- The way to control any \fBUart\fP functions is through this struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uart\&.h>\fP
.SH "Detailed Description"
.PP 
The way to control any \fBUart\fP functions is through this struct\&. 

Use \fBUart\fP like an object when performing operations 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cavrn Sedimentary from the source code\&.
